baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Piyush Patel Website'
theme: 'LoveItCustom'
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
menu:
  main:
    - weight: 10
      identifier: "tutorials"
      name: "Tutorials"
      url: "/tutorials"
      pre: ""
      post: ""
    - weight: 20
      identifier: "about"
      name: "About Us"
      url: "/about"
      pre: ""
      post: ""
params:
  title: "Piyush Blogs"
  description: "Sample description"
  defaultTheme: "auto"
  header:
    title: 
      name: "Piyush Patel"
  page:
    toc: 
      enable: true
      # keepStatic: true
      auto: true
    code:
      copy: true
      maxShownLines: 50
