baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Piyush Patel Website'
theme: 'LoveItCustom'
params:
  title: "Piyush Blogs"
  description: "Sample description"
  header:
    title: 
      name: "Piyush Patel"