services:
  server:
    image: hugomods/hugo:exts-0.147.1
    command: hugo server --bind 0.0.0.0 --disableFastRender -D
    # command: tail -f /dev/null
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - "1313:1313"
